CREATE TABLE `directions` (
   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `time` DOUBLE NOT NULL DEFAULT '0',
   `x` FLOAT NOT NULL DEFAULT '0',
   `z` FLOAT NOT NULL DEFAULT '0'
)
ENGINE=MyISAM;
